### ISSUE TITLE
Draft Questionnaire Feedback

### ISSUE THREAD

**Issue by TheDataAreClean** [The-Data-for-Children-Collaborative/noral-user-research#1]
Feedback on the draft Stakeholder Questionnaire from other Project Partners.

Questionnaire [Link](https://github.com/The-Data-for-Children-Collaborative/noral-platform-research/blob/main/research/01-stakeholder-engagement/01.02-questionnaire.md).

**Comment by grmurray10** [comment]
Q. _Please select the organisation you represent: 
<dropdown> 
- Aberdeen City Council
- Aberdeenshire Council
- Argyll & Bute Council
- Highland Council
- Moray Council
- Orkney Islands Council
- Shetland Islands Council
- Comhairle nan Eilean Siar
- Other(Please specify)_
Grant - _**See amendment above**_

Q. How would you rate the data and/or information you are consuming on the following metrics?

1 being the lowest and 5 being the highest.

Discoverability; ease to search, discover required data and/or information 1 / 2 / 3 / 4 / 5

Usability; ease to analyse and or adopt the data and/or information to fulfill your requirements 1 / 2 / 3 / 4 / 5

Actionability; ease of employ to data to direct or take decisions related to your area of work 1 / 2 / 3 / 4 / 5

Grant - _**I think it might be worthwhile looking at the items above in terms of wording**_


Q. How would you rate the platforms, tools you are consuming on the following metrics?

1 being the lowest and 5 being the highest.

Discoverability; ease to search, discover required data and/or information 1 / 2 / 3 / 4 / 5

Usability; ease to analyse and or adopt the data and/or information to fulfill your requirements 1 / 2 / 3 / 4 / 5

Actionability; ease of employ to data to direct or take decisions related to your area of work 1 / 2 / 3 / 4 / 5

Grant - _**I think it might be worthwhile looking at the items above in terms of wording**_



User Requirements
Q. What kind on data and/or information would you prefer to better understand the state of child education in your region?

Grant - _**Might need to re-visit the wording. It appears a number of times and I am thinking about this**_

**Comment by TheDataAreClean** [comment]
Hey @grmurray10 , thanks for your feedback ! I have incorporated most of it.

A couple of questions:
1. I am assuming the `Select the Northern Alliance Region you belong to.` question is being replaced by `Please select the organisation you represent.` .

2. I have reqorded the complex bits again, do let me know if these work now.

You can review the changes [here](https://github.com/The-Data-for-Children-Collaborative/noral-platform-research/pull/2/files#diff-a41cf306edb5037f00424bd98675a1e25657a1e9f2f15e71c56fe76559c3fe12) .

**Comment by TheDataAreClean** [comment]
Comments from Grant:

Information Sheet:
The research team at CivicDataLab is running this short survey, to understand what kind of information/data you seek/prefer to know about the needs of children and young people in relation to education in your area.

General Comments: 	
Can we have the order of information as follows:

Purpose			
Can we highlight the section about designing a data platform? 
Survey details			
Remove the highlighted bit on time. 
Confidentiality
Do we need to define the duration of how long you will hold this?

Page 2: 
Q7: Is there a way that the scale could be more easily defined, instead of low-high?
Not at all Easy – Very Easy? 
* I wonder if it could also be visualised on a sliding scale. 

Q12: 
Suggested wording: How interested would you be in the following types of data when considering the needs of children & young people in relation to education?
* Also, what is the scale?
* Can we adjust based on some of the ideas around sliding scale? Maybe a sliding scale on preference/interest?

Page 3: 

Q14. Typo
Can we change education space to system?

Q15: 
It might be worth re-iterating that this is a platform that is to be developed – not an existing one.
