### ISSUE TITLE
Feature feedback - Consolidation

### ISSUE THREAD

**Issue by jatinbaghel** [The-Data-for-Children-Collaborative/noral-user-research#9]
- [x] 001-information-mapping.md
- [x] 002-comparative-analysis.md
- [x] 003-data-collection.md
- [x] 004-open-access.md
- [x] 005-data-stories.md
- [x] 006-capacity-building.md

**Comment by TheDataAreClean** [comment]
- Collected all points together.
- Summarisation is pending.

**Comment by TheDataAreClean** [comment]
Edited and briefed all points [here](https://github.com/The-Data-for-Children-Collaborative/noral-user-research/blob/main/02-stakeholder-workshop/feature-feedback/006-capacity-building.md).
